# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0006_auto_20170406_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-timestamp']},
        ),
    ]
