# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0007_auto_20170409_2316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={},
        ),
    ]
