# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0008_auto_20170409_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='facebook_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='charity',
            name='twitter_url',
            field=models.URLField(default=''),
        ),
    ]
