# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0009_auto_20170425_0117'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='http://google.com'),
        ),
    ]
