# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0010_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_image_url',
            field=models.URLField(default='http://google.com'),
        ),
    ]
