# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards_app', '0011_profile_cover_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover_image_url',
            field=models.URLField(default='http://blog.entheosweb.com/wp-content/uploads/2012/03/fbs23_byentheosweb.jpg'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.URLField(default='http://simpleicon.com/wp-content/uploads/account.png'),
        ),
    ]
